version: '3'
services:
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start"
    volumes:
      - .:/qiitan-training
      - bundle:/bundle
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ""
      DATABASE_HOSTNAME: db
      DATABASE_NAME: qiitan-training
    tty: true
    stdin_open: true
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
